languageCode = "en-us"
baseurl = "https://codingdojo.org/"
title = "Coding Dojo"
theme = "template-hugo-codingdojo"
metadataformat = "yaml"
canonifyurls = true
disablePathToLower = true
defaultContentLanguage = "en"
sectionPagesMenu = "main"

[languages]
[languages.en]

[languages.fr]

[languages.pt]
